"""empty message

Revision ID: 72e05ed5f8fc
Revises: 
Create Date: 2026-02-20 20:23:40.107560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e05ed5f8fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('sign_up_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_account')),
    sa.UniqueConstraint('email', name=op.f('uq_account_email')),
    sa.UniqueConstraint('user_name', name=op.f('uq_account_user_name'))
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('problem_text', sa.Text(), nullable=False),
    sa.Column('user_code', sa.Text(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('reference_solution', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], name=op.f('fk_submissions_user_id_account')),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_submissions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('account')
    # ### end Alembic commands ###
