"""empty message

Revision ID: 8446d1870190
Revises: 72e05ed5f8fc
Create Date: 2026-02-25 21:24:30.298916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8446d1870190'
down_revision = '72e05ed5f8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('user_code',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('user_code',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
